flowchart TB
  subgraph Edge
    CF[CloudFront]
  end

  subgraph Frontend
    S3[S3 Bucket (Private) - Static UI]
  end

  subgraph Backend
    API[API Gateway HTTP API]
    L1[Lambda Catalog]
    L2[Lambda Cart]
    L3[Lambda Orders]
    D1[(DynamoDB Cart - OnDemand)]
    D2[(DynamoDB Orders - OnDemand)]
  end

  subgraph Ops
    CW[CloudWatch Logs/Metrics]
    AL[CloudWatch Alarms]
  end

  CF --> S3
  API --> L1
  API --> L2
  API --> L3
  L2 --> D1
  L3 --> D2
  API --> CW
  L1 --> CW
  L2 --> CW
  L3 --> CW
  CW --> AL